# Generated by Django 2.2 on 2020-06-15 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_messages_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 18, 42, 24, 14027, tzinfo=utc)),
        ),
    ]
